<?php

/**
 * BaseInviteRequest
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $email
 * @property string $url
 * @property string $firstname
 * @property string $lastname
 * 
 * @method string        getEmail()     Returns the current record's "email" value
 * @method string        getUrl()       Returns the current record's "url" value
 * @method string        getFirstname() Returns the current record's "firstname" value
 * @method string        getLastname()  Returns the current record's "lastname" value
 * @method InviteRequest setEmail()     Sets the current record's "email" value
 * @method InviteRequest setUrl()       Sets the current record's "url" value
 * @method InviteRequest setFirstname() Sets the current record's "firstname" value
 * @method InviteRequest setLastname()  Sets the current record's "lastname" value
 * 
 * @package    socialhub
 * @subpackage model
 * @author     Sanjeevan Ambalavanar
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseInviteRequest extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('invite_request');
        $this->hasColumn('email', 'string', 100, array(
             'type' => 'string',
             'length' => '100',
             ));
        $this->hasColumn('url', 'string', 100, array(
             'type' => 'string',
             'length' => '100',
             ));
        $this->hasColumn('firstname', 'string', 50, array(
             'type' => 'string',
             'length' => '50',
             ));
        $this->hasColumn('lastname', 'string', 50, array(
             'type' => 'string',
             'length' => '50',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}