<?php

/**
 * BaseBlogEntry
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $user_id
 * @property string $title
 * @property string $summary
 * @property string $summary_html
 * @property string $body
 * @property string $body_html
 * @property string $status
 * @property timestamp $published_at
 * @property User $User
 * 
 * @method integer   getId()           Returns the current record's "id" value
 * @method integer   getUserId()       Returns the current record's "user_id" value
 * @method string    getTitle()        Returns the current record's "title" value
 * @method string    getSummary()      Returns the current record's "summary" value
 * @method string    getSummaryHtml()  Returns the current record's "summary_html" value
 * @method string    getBody()         Returns the current record's "body" value
 * @method string    getBodyHtml()     Returns the current record's "body_html" value
 * @method string    getStatus()       Returns the current record's "status" value
 * @method timestamp getPublishedAt()  Returns the current record's "published_at" value
 * @method User      getUser()         Returns the current record's "User" value
 * @method BlogEntry setId()           Sets the current record's "id" value
 * @method BlogEntry setUserId()       Sets the current record's "user_id" value
 * @method BlogEntry setTitle()        Sets the current record's "title" value
 * @method BlogEntry setSummary()      Sets the current record's "summary" value
 * @method BlogEntry setSummaryHtml()  Sets the current record's "summary_html" value
 * @method BlogEntry setBody()         Sets the current record's "body" value
 * @method BlogEntry setBodyHtml()     Sets the current record's "body_html" value
 * @method BlogEntry setStatus()       Sets the current record's "status" value
 * @method BlogEntry setPublishedAt()  Sets the current record's "published_at" value
 * @method BlogEntry setUser()         Sets the current record's "User" value
 * 
 * @package    socialhub
 * @subpackage model
 * @author     Sanjeevan Ambalavanar
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseBlogEntry extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('blog_entry');
        $this->hasColumn('id', 'integer', 4, array(
             'primary' => true,
             'autoincrement' => true,
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('user_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('summary', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('summary_html', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('body', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('body_html', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('status', 'string', 15, array(
             'type' => 'string',
             'length' => '15',
             ));
        $this->hasColumn('published_at', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('User', array(
             'local' => 'user_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'unique' => true,
             'fields' => 
             array(
              0 => 'title',
             ),
             'canUpdate' => true,
             ));
        $this->actAs($timestampable0);
        $this->actAs($sluggable0);
    }
}