<?php

/**
 * BaseInvite
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $code
 * @property integer $user_id
 * @property enum $status
 * @property timestamp $sent_at
 * @property string $sent_to
 * @property integer $invited_user_id
 * @property User $User
 * 
 * @method string    getCode()            Returns the current record's "code" value
 * @method integer   getUserId()          Returns the current record's "user_id" value
 * @method enum      getStatus()          Returns the current record's "status" value
 * @method timestamp getSentAt()          Returns the current record's "sent_at" value
 * @method string    getSentTo()          Returns the current record's "sent_to" value
 * @method integer   getInvitedUserId()   Returns the current record's "invited_user_id" value
 * @method User      getUser()            Returns the current record's "User" value
 * @method Invite    setCode()            Sets the current record's "code" value
 * @method Invite    setUserId()          Sets the current record's "user_id" value
 * @method Invite    setStatus()          Sets the current record's "status" value
 * @method Invite    setSentAt()          Sets the current record's "sent_at" value
 * @method Invite    setSentTo()          Sets the current record's "sent_to" value
 * @method Invite    setInvitedUserId()   Sets the current record's "invited_user_id" value
 * @method Invite    setUser()            Sets the current record's "User" value
 * 
 * @package    socialhub
 * @subpackage model
 * @author     Sanjeevan Ambalavanar
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseInvite extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('invite');
        $this->hasColumn('code', 'string', 100, array(
             'type' => 'string',
             'length' => '100',
             ));
        $this->hasColumn('user_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('status', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'unused',
              1 => 'sent',
              2 => 'used',
             ),
             'default' => 'unused',
             ));
        $this->hasColumn('sent_at', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('sent_to', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('invited_user_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));


        $this->index('code_index', array(
             'fields' => 
             array(
              0 => 'code',
             ),
             'type' => 'unique',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('User', array(
             'local' => 'user_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}