<?php

/**
 * BaseThing
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property decimal $hot
 * @property integer $ups
 * @property integer $downs
 * @property integer $score
 * @property boolean $is_published
 * @property Article $Article
 * @property Doctrine_Collection $Vote
 * @property Comment $Comment
 * 
 * @method integer             getId()           Returns the current record's "id" value
 * @method decimal             getHot()          Returns the current record's "hot" value
 * @method integer             getUps()          Returns the current record's "ups" value
 * @method integer             getDowns()        Returns the current record's "downs" value
 * @method integer             getScore()        Returns the current record's "score" value
 * @method boolean             getIsPublished()  Returns the current record's "is_published" value
 * @method Article             getArticle()      Returns the current record's "Article" value
 * @method Doctrine_Collection getVote()         Returns the current record's "Vote" collection
 * @method Comment             getComment()      Returns the current record's "Comment" value
 * @method Thing               setId()           Sets the current record's "id" value
 * @method Thing               setHot()          Sets the current record's "hot" value
 * @method Thing               setUps()          Sets the current record's "ups" value
 * @method Thing               setDowns()        Sets the current record's "downs" value
 * @method Thing               setScore()        Sets the current record's "score" value
 * @method Thing               setIsPublished()  Sets the current record's "is_published" value
 * @method Thing               setArticle()      Sets the current record's "Article" value
 * @method Thing               setVote()         Sets the current record's "Vote" collection
 * @method Thing               setComment()      Sets the current record's "Comment" value
 * 
 * @package    socialhub
 * @subpackage model
 * @author     Sanjeevan Ambalavanar
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseThing extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('thing');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => '4',
             ));
        $this->hasColumn('hot', 'decimal', 15, array(
             'type' => 'decimal',
             'scale' => 7,
             'length' => '15',
             ));
        $this->hasColumn('ups', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('downs', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('score', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('is_published', 'boolean', null, array(
             'type' => 'boolean',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Article', array(
             'local' => 'id',
             'foreign' => 'thing_id'));

        $this->hasMany('Vote', array(
             'local' => 'id',
             'foreign' => 'thing_id'));

        $this->hasOne('Comment', array(
             'local' => 'id',
             'foreign' => 'thing_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}