<?php

/**
 * BaseVote
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $thing_id
 * @property integer $user_id
 * @property string $type
 * @property Thing $Thing
 * @property User $User
 * 
 * @method integer getId()       Returns the current record's "id" value
 * @method integer getThingId()  Returns the current record's "thing_id" value
 * @method integer getUserId()   Returns the current record's "user_id" value
 * @method string  getType()     Returns the current record's "type" value
 * @method Thing   getThing()    Returns the current record's "Thing" value
 * @method User    getUser()     Returns the current record's "User" value
 * @method Vote    setId()       Sets the current record's "id" value
 * @method Vote    setThingId()  Sets the current record's "thing_id" value
 * @method Vote    setUserId()   Sets the current record's "user_id" value
 * @method Vote    setType()     Sets the current record's "type" value
 * @method Vote    setThing()    Sets the current record's "Thing" value
 * @method Vote    setUser()     Sets the current record's "User" value
 * 
 * @package    socialhub
 * @subpackage model
 * @author     Sanjeevan Ambalavanar
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseVote extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('vote');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => '4',
             ));
        $this->hasColumn('thing_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('user_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('type', 'string', 4, array(
             'type' => 'string',
             'length' => '4',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Thing', array(
             'local' => 'thing_id',
             'foreign' => 'id'));

        $this->hasOne('User', array(
             'local' => 'user_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}