<?php

/**
 * BaseFileToArticle
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $file_id
 * @property integer $article_id
 * @property boolean $is_published
 * @property File $File
 * @property Article $Article
 * 
 * @method integer       getId()           Returns the current record's "id" value
 * @method integer       getFileId()       Returns the current record's "file_id" value
 * @method integer       getArticleId()    Returns the current record's "article_id" value
 * @method boolean       getIsPublished()  Returns the current record's "is_published" value
 * @method File          getFile()         Returns the current record's "File" value
 * @method Article       getArticle()      Returns the current record's "Article" value
 * @method FileToArticle setId()           Sets the current record's "id" value
 * @method FileToArticle setFileId()       Sets the current record's "file_id" value
 * @method FileToArticle setArticleId()    Sets the current record's "article_id" value
 * @method FileToArticle setIsPublished()  Sets the current record's "is_published" value
 * @method FileToArticle setFile()         Sets the current record's "File" value
 * @method FileToArticle setArticle()      Sets the current record's "Article" value
 * 
 * @package    socialhub
 * @subpackage model
 * @author     Sanjeevan Ambalavanar
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseFileToArticle extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('file_to_article');
        $this->hasColumn('id', 'integer', 4, array(
             'primary' => true,
             'autoincrement' => true,
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('file_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('article_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('is_published', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 0,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('File', array(
             'local' => 'file_id',
             'foreign' => 'id'));

        $this->hasOne('Article', array(
             'local' => 'article_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}