<?php

/**
 * TagToArticle
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    socialhub
 * @subpackage model
 * @author     Sanjeevan Ambalavanar
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class TagToArticle extends BaseTagToArticle
{
}
