<?php

/**
 * User
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    codelovely
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class User extends BaseUser
{
  public function isCorrectPassword($password_plaintext = '')
  {
    if (sha1($this->salt . $password_plaintext) == $this->password)
    {
      return true;
    }
    
    return false;
  }
  
  public function setPlaintextPassword($password)
  {
    $this->salt = myUtil::getRandomSalt(10);
    $this->password = sha1($this->salt . $password);
  }
}
