<?php
/**
 * Adds the _html fields to the article table
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version1 extends Doctrine_Migration_Base
{
  public function up()
  {
    $this->addColumn('article', 'summary_html', 'string', '', array());
    $this->addColumn('article', 'fulldescription_html', 'string', '', array());
    $this->addColumn('article', 'question_html', 'string', '', array());
  }

  public function down()
  {
    $this->removeColumn('article', 'summary_html');
    $this->removeColumn('article', 'fulldescription_html');
    $this->removeColumn('article', 'question_html');
  }
}