<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version2 extends Doctrine_Migration_Base
{
  public function up()
  {
    $this->addColumn('user', 'twitter', 'string', '100', array());
    $this->addColumn('user', 'website_url', 'string', '255', array());
    
    $skills = array(
      0 => 'none', 
      1 => 'developer', 
      2 => 'designer', 
      3 => 'designer_developer'
    );
    
    $this->addColumn('user', 'skills', 'enum', '', array('values' => $skills, 'default' => 'none'));
  }

  public function down()
  {
    $this->removeColumn('user', 'twitter');
    $this->removeColumn('user', 'website_url');
    $this->removeColumn('user', 'skills');
  }
}