<?php

/**
 * sfMessageInbox
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    codelovely
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class sfMessageInbox extends PluginsfMessageInbox
{
  public function markAsRead()
  {
    $this->setLastAccessed(date(myUtil::MYSQL_DATETIME));
    $this->setIsRead(1);
    $this->save();
  }
}
