<?php

/**
 * BasesfMessageInbox
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $user_id
 * @property integer $from_id
 * @property string $to_str
 * @property string $title
 * @property string $message
 * @property boolean $is_read
 * @property timestamp $last_accessed
 * @property User $FromUser
 * @property User $User
 * 
 * @method integer        getId()            Returns the current record's "id" value
 * @method integer        getUserId()        Returns the current record's "user_id" value
 * @method integer        getFromId()        Returns the current record's "from_id" value
 * @method string         getToStr()         Returns the current record's "to_str" value
 * @method string         getTitle()         Returns the current record's "title" value
 * @method string         getMessage()       Returns the current record's "message" value
 * @method boolean        getIsRead()        Returns the current record's "is_read" value
 * @method timestamp      getLastAccessed()  Returns the current record's "last_accessed" value
 * @method User           getFromUser()      Returns the current record's "FromUser" value
 * @method User           getUser()          Returns the current record's "User" value
 * @method sfMessageInbox setId()            Sets the current record's "id" value
 * @method sfMessageInbox setUserId()        Sets the current record's "user_id" value
 * @method sfMessageInbox setFromId()        Sets the current record's "from_id" value
 * @method sfMessageInbox setToStr()         Sets the current record's "to_str" value
 * @method sfMessageInbox setTitle()         Sets the current record's "title" value
 * @method sfMessageInbox setMessage()       Sets the current record's "message" value
 * @method sfMessageInbox setIsRead()        Sets the current record's "is_read" value
 * @method sfMessageInbox setLastAccessed()  Sets the current record's "last_accessed" value
 * @method sfMessageInbox setFromUser()      Sets the current record's "FromUser" value
 * @method sfMessageInbox setUser()          Sets the current record's "User" value
 * 
 * @package    socialhub
 * @subpackage model
 * @author     Sanjeevan Ambalavanar
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BasesfMessageInbox extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('sf_message_inbox');
        $this->hasColumn('id', 'integer', 4, array(
             'primary' => true,
             'autoincrement' => true,
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('user_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('from_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('to_str', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('message', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('is_read', 'boolean', null, array(
             'type' => 'boolean',
             ));
        $this->hasColumn('last_accessed', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('User as FromUser', array(
             'local' => 'from_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('User', array(
             'local' => 'user_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}